esphome:
  name: dish
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

i2c:
  sda: 21
  scl: 22
  scan: true
  id: bus_a

sensor:
  - platform: mpu6050
    address: 0x68
    accel_x:
      name: "MPU6050 Accel X"
    accel_y:
      name: "MPU6050 Accel Y"
    accel_z:
      name: "MPU6050 Accel z"
    gyro_x:
      name: "MPU6050 Gyro X"
    gyro_y:
      name: "MPU6050 Gyro Y"
    gyro_z:
      name: "MPU6050 Gyro z"
    temperature:
      name: "MPU6050 Temperature"
    update_interval: .5s
    
binary_sensor:
  - platform: gpio
    name: "DishWasher door"
    id: physical_button
    pin: 
      number: 32
      mode: INPUT_PULLUP
    on_state:
      then:
        # - switch.toggle: relay_switch
    
ota:
  password: "******"

wifi:
  ssid: "******"
  password: "******"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Dish Fallback Hotspot"
    password: "*****"

captive_portal:

